---
- hosts: '{{ hosts_list }}'

  - name: Create directories
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      owner: {{ working_id }}
      group: {{ working_id }}
    with_items:
      - "{{ working_directory }}"
      - "{{ working_directory }}/relay/conf_files/testnet"
      - "{{ working_directory }}/cardanodb"
      - "{{ working_directory }}/keysandaddresses"

  - name: Download config files
    ansible.builtin.get_url:
      url: "https://hydra.iohk.io/job/Cardano/cardano-node/cardano-deployment/latest-finished/download/1/{{ item }}"
      dest: "{{ working_directory }}/relay/conf_files/testnet/{{item}}"
      owner: {{ working_id }}
      group: {{ working_id }}
    with_items: {{ cardano_node_config_files }}
      
  - name: Update cache
    ansible.builtin.apt:
      update_cache: yes
  
  - name: Install docker
    ansible.builtin.apt:
      update_cache: yes
  
  - name: Create network
    ansible.builtin.docker_network:
      name: tx-network
  
  - name: Start node
    ansible.builtin.docker_container:
      image: inputoutput/cardano-node:{{ cardano_node_version }}
      name: cardano-node
      hostname: cardano-node
      container_default_behavior: no_defaults
      networks:
        - name: "tx-network"
      volumes:
        - {{ working_directory }}/cardanodb:/var/lib/cardanodb
        - {{ working_directory }}/relay/conf_files/testnet:/etc/cardano-node:ro
        - {{ working_directory }}/keysandaddresses:/var/lib/keysandaddresses:ro
      ports:
        - "3001:3001"
      command: run --topology /etc/cardano-node/testnet-topology.json \
                --database-path /var/lib/cardanodb \
                --socket-path /var/lib/cardanodb/node.socket \
                --host-addr 0.0.0.0\
                --port 3001 \
                --config /etc/cardano-node/testnet-config.json
